global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "k8-llmbenchmark"
    scrape_interval: 5s
    static_configs:
      - targets: ["k8-llmbenchmark-service.default.svc.cluster.local:8000"]
